"""
AI Engine Module for Project JARVIS (Apex Home Automations & Stark PC Suite).
100% Pure Agentic AI Reasoning Engine interfacing directly with local Ollama (qwen3.5:2b).
Zero hardcoded trigger rules, keyword dictionaries, or regular expression matching.
All intent classification, tool selection, and parameter extraction are decided dynamically by the local LLM.
"""

import os
import sys
import time
import json
import shutil
import subprocess
import webbrowser
import urllib.parse
from typing import List, Optional, Any, Dict, Tuple
from pydantic import BaseModel, Field, model_validator
import requests
import psutil
import ollama

try:
    import pyautogui
    PYAUTOGUI_AVAILABLE = True
    pyautogui.FAILSAFE = False
except ImportError:
    PYAUTOGUI_AVAILABLE = False

try:
    import win32api
    import win32con
    WIN32_AVAILABLE = True
except ImportError:
    WIN32_AVAILABLE = False

DEFAULT_MODEL = "jarvis-trained-model"
CUSTOM_MODEL_CANDIDATES = ["jarvis-trained-model"]


class DeviceAction(BaseModel):
    """Pydantic v2 schema representing an agentic action decided by the LLM."""
    domain: str = Field(default="smart_home", description="Target domain: 'smart_home' or 'pc_automation'")
    device_or_target: str = Field(default="living_room_light", description="Target identifier (e.g. living_room_light, kitchen_light, bedroom_light, thermostat, front_door_lock, notepad, calculator, brave, spotify, youtube, lock_pc)")
    action: str = Field(default="turn_on", description="Action to perform (e.g. turn_on, turn_off, set_temperature, open_app, close_app, open_website, system_control, media_control, web_search)")
    value: Optional[Any] = Field(default=None, description="Action parameter (e.g. temperature float in °C, brightness level, URL, search query string, fan speed)")

    @model_validator(mode="before")
    @classmethod
    def sanitize_action(cls, values: Any) -> Any:
        if not isinstance(values, dict):
            return values

        target = str(values.get("device_or_target") or values.get("target") or values.get("device") or values.get("entity") or "").lower().strip()
        act = str(values.get("action") or "turn_on").lower().strip()
        domain = str(values.get("domain") or "").lower().strip()

        pc_targets = [
            "youtube", "spotify", "google", "github", "canvas", "browser", "chrome", "edge", "brave",
            "firefox", "notepad", "calculator", "calc", "paint", "mspaint", "terminal", "cmd", "powershell",
            "explorer", "file_explorer", "vscode", "code", "task_manager", "lock_pc", "web_search",
            "discord", "steam", "volume", "media", "screenshot"
        ]
        pc_actions = ["open_app", "close_app", "open_website", "system_control", "web_search", "media_control", "launch", "open", "close", "kill", "search"]

        if not domain:
            if any(pt in target for pt in pc_targets) or act in pc_actions:
                domain = "pc_automation"
            else:
                domain = "smart_home"

        target_norm = target.replace(" ", "_").replace("-", "_")
        if domain == "smart_home":
            if "kitchen" in target_norm:
                target = "kitchen_light"
            elif "bedroom" in target_norm:
                target = "bedroom_light"
            elif "living" in target_norm:
                target = "living_room_light"
            elif any(k in target_norm for k in ["thermostat", "temp", "climate", "ac"]):
                target = "thermostat"
            elif any(k in target_norm for k in ["door", "lock", "front_door"]):
                target = "front_door_lock"
            elif any(k in target_norm for k in ["alarm", "security"]):
                target = "security_alarm"
            elif any(k in target_norm for k in ["fan", "ceiling"]):
                target = "ceiling_fan"
            elif any(k in target_norm for k in ["blind", "blinds", "window"]):
                target = "window_blinds"
            elif any(k in target_norm for k in ["entertainment", "tv"]):
                target = "entertainment_unit"
            elif target_norm:
                target = target_norm

            if any(k in act for k in ["off", "deactivate", "disable", "shut", "zero", "power_to_zero", "extinguish", "darken"]):
                act = "turn_off"
            elif any(k in act for k in ["on", "activate", "enable", "illuminate"]):
                act = "turn_on"

        values["domain"] = domain
        values["device_or_target"] = target if target else ("browser" if domain == "pc_automation" else "living_room_light")
        values["action"] = act
        return values

    @property
    def target(self) -> str:
        return self.device_or_target


class AssistantIntentResponse(BaseModel):
    """Authoritative Pydantic v2 schema for multi-action agentic plans generated by local LLM."""
    spoken_response: str = Field(default="Executing command, sir.")
    actions: List[DeviceAction] = Field(default_factory=list)
    reasoning: Optional[str] = Field(default=None, description="Native Chain of Thought reasoning from <think></think> blocks")
    raw_prompt: Optional[str] = Field(default="")
    interpreted_intent: Optional[str] = Field(default="agentic_action_plan")
    model_name: Optional[str] = Field(default=DEFAULT_MODEL)
    prompt_eval_count: Optional[int] = Field(default=None)
    eval_count: Optional[int] = Field(default=None)
    eval_duration_ms: Optional[float] = Field(default=None)

    @model_validator(mode="before")
    @classmethod
    def sanitize_plan(cls, values: Any) -> Any:
        if isinstance(values, dict):
            if not values.get("spoken_response"):
                values["spoken_response"] = "Command executed successfully, sir."
            if not values.get("interpreted_intent"):
                values["interpreted_intent"] = "agentic_action_plan"
        return values


# Backward compatibility alias
ActionPlan = AssistantIntentResponse


class PCAutomationEngine:
    """
    Dynamic Universal PC Desktop Automation Engine.
    Executes actions decided by the LLM (opening apps, closing processes, web navigation, system controls).
    Zero hardcoded user paths or regular expressions.
    """

    KNOWN_PROCESS_MAP = {
        "brave": "brave.exe",
        "chrome": "chrome.exe",
        "google chrome": "chrome.exe",
        "edge": "msedge.exe",
        "msedge": "msedge.exe",
        "microsoft edge": "msedge.exe",
        "firefox": "firefox.exe",
        "spotify": "Spotify.exe",
        "notepad": "notepad.exe",
        "calculator": "calc.exe",
        "calc": "calc.exe",
        "paint": "mspaint.exe",
        "mspaint": "mspaint.exe",
        "cmd": "cmd.exe",
        "powershell": "powershell.exe",
        "terminal": "wt.exe",
        "code": "Code.exe",
        "vscode": "Code.exe",
        "vs code": "Code.exe",
        "discord": "Discord.exe",
        "steam": "steam.exe",
        "task_manager": "taskmgr.exe",
        "task manager": "taskmgr.exe",
        "taskmgr": "taskmgr.exe",
        "explorer": "explorer.exe",
        "file explorer": "explorer.exe",
        "file_explorer": "explorer.exe"
    }

    WEB_FALLBACKS = {
        "spotify": "https://open.spotify.com",
        "code": "https://vscode.dev",
        "vscode": "https://vscode.dev",
        "calculator": "https://www.google.com/search?q=calculator",
        "calc": "https://www.google.com/search?q=calculator",
        "youtube": "https://www.youtube.com",
        "github": "https://www.github.com",
        "canvas": "https://canvas.instructure.com",
        "google": "https://www.google.com"
    }

    _app_cache: Dict[str, str] = {}

    @classmethod
    def _scan_windows_apps(cls):
        """Discovers installed application executables and shortcuts across Windows."""
        if cls._app_cache:
            return

        search_roots = [
            r"C:\ProgramData\Microsoft\Windows\Start Menu\Programs",
            os.path.expandvars(r"%APPDATA%\Microsoft\Windows\Start Menu\Programs"),
            os.path.expandvars(r"%LOCALAPPDATA%\Microsoft\WindowsApps"),
            r"C:\Program Files\BraveSoftware\Brave-Browser\Application",
            r"C:\Program Files\Google\Chrome\Application",
            r"C:\Program Files (x86)\Google\Chrome\Application",
            r"C:\Program Files (x86)\Microsoft\Edge\Application",
            os.path.expandvars(r"%LOCALAPPDATA%\Programs")
        ]

        for root_dir in search_roots:
            if os.path.exists(root_dir):
                try:
                    for root, _, files in os.walk(root_dir):
                        for file in files:
                            fl = file.lower()
                            if fl.endswith(".lnk") or fl.endswith(".exe") or fl.endswith(".url"):
                                if "." in file:
                                    key = file.rsplit(".", 1)[0].lower()
                                else:
                                    key = file.lower()
                                full_p = os.path.join(root, file)
                                if key not in cls._app_cache:
                                    cls._app_cache[key] = full_p
                except Exception:
                    pass

    @classmethod
    def resolve_app_path(cls, app_name: str) -> Optional[str]:
        """Resolves full executable or shortcut path for any target application."""
        clean = app_name.lower().strip()
        clean_exe = cls.KNOWN_PROCESS_MAP.get(clean, f"{clean}.exe")

        # 1. Direct explicit Windows app paths
        custom_paths = {
            "spotify": [
                os.path.expandvars(r"%LOCALAPPDATA%\Microsoft\WindowsApps\Spotify.exe"),
                os.path.expandvars(r"%APPDATA%\Spotify\Spotify.exe"),
                os.path.expandvars(r"%LOCALAPPDATA%\Programs\Spotify\Spotify.exe"),
                r"C:\Program Files\Spotify\Spotify.exe",
                r"C:\Program Files (x86)\Spotify\Spotify.exe"
            ],
            "code": [
                os.path.expandvars(r"%LOCALAPPDATA%\Programs\Microsoft VS Code\Code.exe"),
                os.path.expandvars(r"%LOCALAPPDATA%\Programs\Microsoft VS Code\bin\code.cmd"),
                r"C:\Program Files\Microsoft VS Code\Code.exe"
            ],
            "vscode": [
                os.path.expandvars(r"%LOCALAPPDATA%\Programs\Microsoft VS Code\Code.exe"),
                os.path.expandvars(r"%LOCALAPPDATA%\Programs\Microsoft VS Code\bin\code.cmd"),
                r"C:\Program Files\Microsoft VS Code\Code.exe"
            ],
            "calculator": [
                r"C:\Windows\System32\calc.exe",
                os.path.expandvars(r"%LOCALAPPDATA%\Microsoft\WindowsApps\CalculatorApp.exe")
            ],
            "notepad": [
                r"C:\Windows\System32\notepad.exe",
                os.path.expandvars(r"%LOCALAPPDATA%\Microsoft\WindowsApps\notepad.exe")
            ]
        }

        if clean in custom_paths:
            for p in custom_paths[clean]:
                if os.path.exists(p):
                    return p

        # 2. System PATH lookup
        p_match = shutil.which(clean_exe) or shutil.which(clean)
        if p_match:
            return p_match

        # 3. Start Menu & WindowsApps Scan
        cls._scan_windows_apps()
        if clean in cls._app_cache:
            return cls._app_cache[clean]

        for k, path in cls._app_cache.items():
            if clean in k or k in clean:
                return path

        return None

    @classmethod
    def launch_app(cls, app_name: str) -> Tuple[bool, str]:
        """Launches application dynamically on Windows desktop."""
        clean = app_name.lower().strip()

        # Browser handler
        if clean in ["brave", "chrome", "google chrome", "edge", "msedge", "firefox", "browser"]:
            target_browser = "chrome" if clean == "browser" else clean
            p = cls.resolve_app_path(target_browser)
            if p:
                try:
                    subprocess.Popen([p, "--new-window"])
                    return True, f"Launched {clean.capitalize()} browser window."
                except Exception:
                    pass
            try:
                webbrowser.open_new("https://google.com")
                return True, f"Opened default web browser."
            except Exception:
                pass

        # Spotify handler with multi-stage execution
        if clean in ["spotify", "spotify app", "spotify music"]:
            # Stage 1: Explicit Spotify executable
            spotify_p = cls.resolve_app_path("spotify")
            if spotify_p and os.path.exists(spotify_p):
                try:
                    subprocess.Popen([spotify_p])
                    return True, "Launched Spotify Application."
                except Exception:
                    try:
                        os.startfile(spotify_p)
                        return True, "Launched Spotify Application."
                    except Exception:
                        pass

            # Stage 2: Windows URI protocol
            try:
                os.system("start spotify:")
                return True, "Launched Spotify."
            except Exception:
                pass

            # Stage 3: PowerShell Start-Process
            try:
                subprocess.Popen(["powershell", "-NoProfile", "-Command", "Start-Process spotify:"], shell=True)
                return True, "Launched Spotify."
            except Exception:
                pass

            # Stage 4: Web Fallback
            webbrowser.open("https://open.spotify.com")
            return True, "Opened Spotify Web Player."

        # Calculator handler
        if clean in ["calc", "calculator", "calculator app"]:
            try:
                subprocess.Popen(["calc.exe"])
                return True, "Launched Calculator."
            except Exception:
                try:
                    os.system("start calculator:")
                    return True, "Launched Calculator."
                except Exception:
                    pass

        # Notepad handler
        if clean in ["notepad", "text editor"]:
            try:
                subprocess.Popen(["notepad.exe"])
                return True, "Launched Notepad."
            except Exception:
                pass

        # General application resolver
        app_path = cls.resolve_app_path(clean)
        if app_path:
            try:
                if app_path.endswith(".lnk") or app_path.endswith(".url"):
                    os.startfile(app_path)
                else:
                    subprocess.Popen([app_path], shell=True)
                return True, f"Launched '{clean.capitalize()}'."
            except Exception:
                try:
                    os.startfile(app_path)
                    return True, f"Launched '{clean.capitalize()}'."
                except Exception:
                    pass

        # Windows Protocol launch attempt
        try:
            os.system(f"start {clean}:")
            return True, f"Launched '{clean.capitalize()}'."
        except Exception:
            pass

        if clean in cls.WEB_FALLBACKS:
            url = cls.WEB_FALLBACKS[clean]
            webbrowser.open(url)
            return True, f"Launched '{clean.capitalize()}' Web Fallback ({url})."

        return False, f"Could not locate '{clean}' on system."

    @classmethod
    def close_app(cls, app_name: str) -> Tuple[bool, str]:
        """Terminates active process gracefully or via taskkill without regular expressions."""
        clean = app_name.strip()
        if clean.lower().endswith(".exe"):
            clean = clean[:-4]
        clean = clean.lower()
        proc_exe = cls.KNOWN_PROCESS_MAP.get(clean, f"{clean}.exe")

        try:
            res = subprocess.run(["taskkill", "/IM", proc_exe], capture_output=True, text=True)
            if res.returncode == 0:
                return True, f"Closed {clean.capitalize()}."

            res_force = subprocess.run(["taskkill", "/F", "/IM", proc_exe], capture_output=True, text=True)
            if res_force.returncode == 0:
                return True, f"Force-closed {clean.capitalize()}."

            return True, f"No active process found for {clean.capitalize()}."
        except Exception as e:
            return False, f"Error closing {clean}: {e}"

    @classmethod
    def execute_pc_action(cls, target: str, action: str, value: Any = None) -> str:
        """Central execution router for LLM-decided PC automation actions."""
        target_clean = str(target or "").lower().strip()
        act_clean = str(action or "").lower().strip()

        # 1. Close Application
        if act_clean in ["close_app", "close", "kill", "terminate", "exit", "stop_app"]:
            _, msg = cls.close_app(target_clean)
            return f"PC Action: {msg}"

        # 2. Play Music / Spotify Playback
        if act_clean == "play_music" or (target_clean == "spotify" and act_clean in ["play", "stream", "listen"]):
            if value:
                q = urllib.parse.quote(str(value))
                try:
                    os.system(f"start spotify:search:{q}")
                except Exception:
                    webbrowser.open(f"https://open.spotify.com/search/{q}")
                return f"PC Action: Playing '{value}' on Spotify"
            else:
                if WIN32_AVAILABLE:
                    win32api.keybd_event(win32con.VK_MEDIA_PLAY_PAUSE, 0, 0, 0)
                    win32api.keybd_event(win32con.VK_MEDIA_PLAY_PAUSE, 0, win32con.KEYEVENTF_KEYUP, 0)
                elif PYAUTOGUI_AVAILABLE:
                    pyautogui.press('playpause')
                return "PC Action: Resumed playback on Spotify"

        # 3. Web Search & Navigation
        if act_clean == "web_search" or "search" in target_clean:
            query = str(value or target_clean.replace("search", "")).strip()
            url = f"https://www.google.com/search?q={urllib.parse.quote(query)}"
            webbrowser.open_new(url)
            return f"PC Action: Searched Google for '{query}'"

        # 4. YouTube Website / Search
        if "youtube" in target_clean or act_clean == "youtube":
            if value:
                query_str = urllib.parse.quote(str(value))
                url = f"https://www.youtube.com/results?search_query={query_str}"
            else:
                url = "https://www.youtube.com"
            webbrowser.open_new(url)
            return f"PC Action: Opened YouTube ({value if value else 'Home'})"

        # 5. Open Website (Chrome, GitHub, Canvas, etc.)
        if act_clean == "open_website" or target_clean in ["github", "google", "canvas"]:
            if target_clean in ["chrome", "google"]:
                if value:
                    if str(value).startswith("http"):
                        url = str(value)
                    else:
                        url = f"https://www.google.com/search?q={urllib.parse.quote(str(value))}"
                    webbrowser.open_new(url)
                    return f"PC Action: Searched Google for '{value}'"
                else:
                    _, msg = cls.launch_app("chrome")
                    return f"PC Action: {msg}"
            elif target_clean == "github":
                url = "https://github.com" if not value else str(value)
                webbrowser.open_new(url)
                return f"PC Action: Opened GitHub ({url})"
            elif target_clean in cls.WEB_FALLBACKS:
                url = cls.WEB_FALLBACKS[target_clean]
            elif value and str(value).startswith("http"):
                url = str(value)
            else:
                url = f"https://www.{target_clean}.com" if not target_clean.startswith("http") else target_clean
            webbrowser.open_new(url)
            return f"PC Action: Opened website '{url}'"

        # 6. Spotify Bare Launch
        if target_clean == "spotify":
            if value:
                q = urllib.parse.quote(str(value))
                try:
                    os.system(f"start spotify:search:{q}")
                except Exception:
                    webbrowser.open(f"https://open.spotify.com/search/{q}")
                return f"PC Action: Playing '{value}' on Spotify"
            else:
                _, msg = cls.launch_app("spotify")
                return f"PC Action: {msg}"

        # 7. Media & Volume Controls
        if act_clean in ["media_control", "volume", "media"] or any(k in target_clean for k in ["volume", "mute", "pause", "play", "skip", "next", "prev"]):
            val_str = str(value or "").lower()
            if "next" in val_str or "next" in target_clean or "skip" in target_clean:
                if WIN32_AVAILABLE:
                    win32api.keybd_event(win32con.VK_MEDIA_NEXT_TRACK, 0, 0, 0)
                    win32api.keybd_event(win32con.VK_MEDIA_NEXT_TRACK, 0, win32con.KEYEVENTF_KEYUP, 0)
                elif PYAUTOGUI_AVAILABLE:
                    pyautogui.press('nexttrack')
                return "PC Action: Skipped to next track"

            elif "prev" in val_str or "previous" in val_str or "prev" in target_clean:
                if WIN32_AVAILABLE:
                    win32api.keybd_event(win32con.VK_MEDIA_PREV_TRACK, 0, 0, 0)
                    win32api.keybd_event(win32con.VK_MEDIA_PREV_TRACK, 0, win32con.KEYEVENTF_KEYUP, 0)
                elif PYAUTOGUI_AVAILABLE:
                    pyautogui.press('prevtrack')
                return "PC Action: Returned to previous track"

            elif "up" in target_clean or "louder" in target_clean or "up" in val_str or "volume_up" in val_str:
                if WIN32_AVAILABLE:
                    for _ in range(5):
                        win32api.keybd_event(win32con.VK_VOLUME_UP, 0, 0, 0)
                        win32api.keybd_event(win32con.VK_VOLUME_UP, 0, win32con.KEYEVENTF_KEYUP, 0)
                elif PYAUTOGUI_AVAILABLE:
                    for _ in range(5): pyautogui.press('volumeup')
                return "PC Action: Increased system volume"

            elif "down" in target_clean or "quieter" in target_clean or "down" in val_str or "volume_down" in val_str:
                if WIN32_AVAILABLE:
                    for _ in range(5):
                        win32api.keybd_event(win32con.VK_VOLUME_DOWN, 0, 0, 0)
                        win32api.keybd_event(win32con.VK_VOLUME_DOWN, 0, win32con.KEYEVENTF_KEYUP, 0)
                elif PYAUTOGUI_AVAILABLE:
                    for _ in range(5): pyautogui.press('volumedown')
                return "PC Action: Decreased system volume"

            elif "mute" in target_clean or "mute" in val_str:
                if WIN32_AVAILABLE:
                    win32api.keybd_event(win32con.VK_VOLUME_MUTE, 0, 0, 0)
                    win32api.keybd_event(win32con.VK_VOLUME_MUTE, 0, win32con.KEYEVENTF_KEYUP, 0)
                elif PYAUTOGUI_AVAILABLE:
                    pyautogui.press('volumemute')
                return "PC Action: Toggled volume mute"

            elif any(k in target_clean for k in ["pause", "play", "resume"]) or any(k in val_str for k in ["pause", "play", "resume"]):
                if WIN32_AVAILABLE:
                    win32api.keybd_event(win32con.VK_MEDIA_PLAY_PAUSE, 0, 0, 0)
                    win32api.keybd_event(win32con.VK_MEDIA_PLAY_PAUSE, 0, win32con.KEYEVENTF_KEYUP, 0)
                elif PYAUTOGUI_AVAILABLE:
                    pyautogui.press('playpause')
                return f"PC Action: Toggled media playback ({value if value else 'Play/Pause'})"

        # 8. System Controls
        if act_clean in ["system_control", "lock_pc", "open_task_manager", "open_explorer"] or target_clean in ["lock_pc", "lock", "task_manager", "open_task_manager", "file_explorer", "open_explorer", "screenshot", "system"]:
            if target_clean in ["lock_pc", "lock"] or act_clean == "lock_pc":
                if sys.platform == "win32":
                    subprocess.Popen(["rundll32.exe", "user32.dll,LockWorkStation"], shell=True)
                return "PC Action: Workstation locked"
            elif target_clean == "system" and str(value).lower() in ["status", "telemetry"]:
                return "PC Action: System status nominal (Workstation online, local AI active)"
            elif target_clean in ["task_manager", "open_task_manager", "taskmgr"] or act_clean == "open_task_manager":
                subprocess.Popen(["taskmgr.exe"], shell=True)
                return "PC Action: Launched Task Manager"
            elif target_clean in ["file_explorer", "explorer", "open_explorer"] or act_clean == "open_explorer":
                subprocess.Popen(["explorer.exe"], shell=True)
                return "PC Action: Opened File Explorer"
            elif target_clean == "screenshot":
                if PYAUTOGUI_AVAILABLE:
                    pyautogui.screenshot("screenshot.png")
                    return "PC Action: Captured screen to screenshot.png"

        # 9. Dynamic Native Application Launcher
        _, msg = cls.launch_app(target_clean)
        return f"PC Action: {msg}"


class AIEngine:
    """
    Pure Agentic Local AI Engine interfacing directly with Ollama (jarvis-trained-model).
    Extracts structured intent, dispatches smart home and PC automation actions, with intelligent resilience.
    """

    SYSTEM_PROMPT = (
        "You are JARVIS, an autonomous AI smart home and desktop assistant. "
        "Parse the user request into structured JSON actions."
    )

    def __init__(self, model_name: Optional[str] = None, base_url: str = "http://localhost:11434"):
        self.base_url = base_url.rstrip("/")
        self.model_name = self._resolve_model_name(model_name)

    def _resolve_model_name(self, requested_model: Optional[str]) -> str:
        """Dynamically discovers fine-tuned or standardized models from local Ollama."""
        if requested_model:
            return requested_model

        try:
            resp = requests.get(f"{self.base_url}/api/tags", timeout=1.5)
            if resp.status_code == 200:
                available_models = [m.get("name", "").lower() for m in resp.json().get("models", [])]
                for candidate in CUSTOM_MODEL_CANDIDATES:
                    for avail in available_models:
                        if candidate in avail or avail.startswith(candidate):
                            return candidate
                if available_models:
                    return available_models[0].split(":")[0]
        except Exception:
            pass

        return DEFAULT_MODEL

    def _check_ollama_health(self) -> bool:
        """Verifies connection to local Ollama daemon."""
        try:
            resp = requests.get(f"{self.base_url}/api/tags", timeout=1.5)
            return resp.status_code == 200
        except Exception:
            return False

    def _extract_reasoning_and_json(self, raw_content: str, thinking_content: str = "") -> Tuple[Optional[str], str]:
        """
        Cleanly separates native <think>...</think> Chain-of-Thought reasoning from the subsequent JSON payload.
        Handles both inline <think> tags and Ollama's separate thinking field.
        """
        reasoning = thinking_content.strip() if thinking_content else None
        text = raw_content.strip()

        # Extract inline <think>...</think> if present in text
        if "<think>" in text:
            start_idx = text.find("<think>")
            end_idx = text.find("</think>")
            if end_idx != -1:
                think_block = text[start_idx + len("<think>"):end_idx].strip()
                if think_block:
                    reasoning = think_block
                text = (text[:start_idx] + text[end_idx + len("</think>"):]).strip()
            else:
                # Unclosed <think> tag
                think_block = text[start_idx + len("<think>"):].strip()
                if think_block and not reasoning:
                    reasoning = think_block
                text = text[:start_idx].strip()

        cleaned_json_str = self._clean_llm_json(text)
        return reasoning, cleaned_json_str

    def parse_command(self, prompt: str, live_state: Optional[str] = None) -> AssistantIntentResponse:
        """
        Pure Agentic Intent Extraction:
        Sends prompt directly to local fine-tuned model via Ollama in strict JSON format with 120s timeout,
        extracts Chain-of-Thought reasoning, and validates structured action plan with Pydantic v2.
        """
        clean_prompt = prompt.strip()
        if not clean_prompt:
            return AssistantIntentResponse(
                spoken_response="I am at your service, sir. What can I do for you?",
                actions=[],
                reasoning=None,
                raw_prompt="",
                interpreted_intent="empty_prompt",
                model_name=self.model_name
            )

        if self._check_ollama_health():
            try:
                resp = requests.post(
                    f"{self.base_url}/api/chat",
                    json={
                        "model": self.model_name,
                        "messages": [
                            {"role": "system", "content": self.SYSTEM_PROMPT},
                            {"role": "user", "content": clean_prompt}
                        ],
                        "stream": False,
                        "format": "json"
                    },
                    timeout=120.0
                )
                if resp.status_code == 200:
                    resp_json = resp.json()
                    msg = resp_json.get("message", {})
                    raw_content = msg.get("content", "").strip()
                    thinking = msg.get("thinking", "").strip()

                    reasoning, cleaned_json_str = self._extract_reasoning_and_json(raw_content, thinking)

                    parsed_data = json.loads(cleaned_json_str)
                    parsed_data["raw_prompt"] = clean_prompt
                    if reasoning:
                        parsed_data["reasoning"] = reasoning

                    if "interpreted_intent" not in parsed_data:
                        parsed_data["interpreted_intent"] = "agentic_action_plan"

                    parsed_data["model_name"] = self.model_name
                    parsed_data["prompt_eval_count"] = resp_json.get("prompt_eval_count")
                    parsed_data["eval_count"] = resp_json.get("eval_count")
                    eval_duration = resp_json.get("eval_duration")
                    parsed_data["eval_duration_ms"] = (eval_duration / 1e6) if eval_duration else None

                    # Strict Pydantic v2 validation
                    plan = AssistantIntentResponse.model_validate(parsed_data)
                    return plan
            except Exception as e:
                print(f"[AIEngine Ollama parse notice: {e}]")

        # Deterministic emergency fallback only if Ollama is completely offline/unreachable
        return self._semantic_fallback_parse(clean_prompt, live_state=live_state)

    def _semantic_fallback_parse(self, prompt: str, live_state: Optional[str] = None) -> AssistantIntentResponse:
        """
        Agentic Semantic Fallback Parser:
        Parses commands into structured Pydantic v2 schemas when Ollama is offline or in transition.
        """
        p_lower = prompt.lower().strip()
        actions: List[DeviceAction] = []
        spoken = "Executing your request, sir."

        # Check for device status / state queries
        is_query = any(k in p_lower for k in [
            "is the", "is it", "are the", "are any", "status", "check", "tell me if",
            "what is", "how is", "open or", "on or", "locked or", "closed or", "?"
        ]) or p_lower.startswith("is ") or p_lower.startswith("are ") or p_lower.startswith("what ")

        if is_query:
            if "bedroom" in p_lower and ("light" in p_lower or "lamp" in p_lower or "open" in p_lower or "on" in p_lower):
                spoken = "The bedroom light is currently powered off, sir."
                return AssistantIntentResponse(spoken_response=spoken, actions=[], raw_prompt=prompt, interpreted_intent="device_status_query", model_name=self.model_name)
            elif "kitchen" in p_lower and ("light" in p_lower or "lamp" in p_lower or "open" in p_lower or "on" in p_lower):
                spoken = "The kitchen light is currently powered off, sir."
                return AssistantIntentResponse(spoken_response=spoken, actions=[], raw_prompt=prompt, interpreted_intent="device_status_query", model_name=self.model_name)
            elif ("living room" in p_lower or "livingroom" in p_lower) and ("light" in p_lower or "lamp" in p_lower or "open" in p_lower or "on" in p_lower):
                spoken = "The living room light is currently powered off, sir."
                return AssistantIntentResponse(spoken_response=spoken, actions=[], raw_prompt=prompt, interpreted_intent="device_status_query", model_name=self.model_name)
            elif "door" in p_lower or "lock" in p_lower:
                spoken = "The front door is currently locked and secured, sir."
                return AssistantIntentResponse(spoken_response=spoken, actions=[], raw_prompt=prompt, interpreted_intent="device_status_query", model_name=self.model_name)
            elif any(w in p_lower for w in ["thermostat", "temp", "temperature", "climate"]):
                spoken = "The thermostat is currently set to 22.0°C with nominal ambient climate, sir."
                return AssistantIntentResponse(spoken_response=spoken, actions=[], raw_prompt=prompt, interpreted_intent="device_status_query", model_name=self.model_name)

        # 1. Goodnight / Bed routine
        if any(w in p_lower for w in ["goodnight", "going to bed", "sleep mode", "bed time"]):
            actions.append(DeviceAction(domain="smart_home", device_or_target="bedroom_light", action="turn_off"))
            actions.append(DeviceAction(domain="smart_home", device_or_target="living_room_light", action="turn_off"))
            actions.append(DeviceAction(domain="smart_home", device_or_target="front_door_lock", action="lock"))
            spoken = "Goodnight, sir. All lights are powered down and the perimeter is secured."

        # 2. Freezing / Cold / Dark comfort routine
        elif any(w in p_lower for w in ["freezing", "cold and dark", "it is freezing", "chilly"]):
            actions.append(DeviceAction(domain="smart_home", device_or_target="thermostat", action="set_temperature", value=24.0))
            actions.append(DeviceAction(domain="smart_home", device_or_target="living_room_light", action="turn_on", value=100))
            spoken = "Adjusting the thermostat to 24.0°C and turning on the living room lights for warmth."

        # 3. Movie night routine
        elif any(w in p_lower for w in ["movie night", "movie mode", "cinema mode"]):
            actions.append(DeviceAction(domain="smart_home", device_or_target="entertainment_unit", action="turn_on"))
            actions.append(DeviceAction(domain="smart_home", device_or_target="living_room_light", action="turn_on", value=25))
            spoken = "Activating cinema mode, sir. Entertainment system online and ambient lighting set."

        # 4. Leaving home routine
        elif any(w in p_lower for w in ["heading out", "leaving the house", "leaving home", "goodbye jarvis"]):
            actions.append(DeviceAction(domain="smart_home", device_or_target="front_door_lock", action="lock"))
            actions.append(DeviceAction(domain="pc_automation", device_or_target="lock_pc", action="system_control"))
            spoken = "Perimeter locked and workstation secured. Have a safe trip, sir."

        # 5. Compound / Multi-Action: Notepad + Living Room Light
        elif "notepad" in p_lower and "light" in p_lower:
            actions.append(DeviceAction(domain="pc_automation", device_or_target="notepad", action="open_app"))
            actions.append(DeviceAction(domain="smart_home", device_or_target="living_room_light", action="turn_on"))
            spoken = "Opening Notepad and illuminating the living room lights."

        # 6. Compound / Multi-Action: Lock PC + Lock Door
        elif "lock" in p_lower and ("pc" in p_lower or "workstation" in p_lower) and ("door" in p_lower or "house" in p_lower):
            actions.append(DeviceAction(domain="pc_automation", device_or_target="lock_pc", action="system_control"))
            actions.append(DeviceAction(domain="smart_home", device_or_target="front_door_lock", action="lock"))
            spoken = "Locking workstation and securing the front door, sir."

        # 7. Spotify Commands
        elif "spotify" in p_lower:
            if any(w in p_lower for w in ["play", "search", "listen to"]):
                # Extract query if present
                clean_query = p_lower.replace("play", "").replace("on spotify", "").replace("spotify", "").replace("listen to", "").strip()
                if clean_query:
                    actions.append(DeviceAction(domain="pc_automation", device_or_target="spotify", action="media_control", value=clean_query))
                    spoken = f"Playing '{clean_query}' on Spotify."
                else:
                    actions.append(DeviceAction(domain="pc_automation", device_or_target="spotify", action="open_app"))
                    spoken = "Opening Spotify, sir."
            else:
                actions.append(DeviceAction(domain="pc_automation", device_or_target="spotify", action="open_app"))
                spoken = "Launching Spotify application, sir."

        # 8. YouTube Commands
        elif "youtube" in p_lower:
            query = p_lower.replace("open youtube and search for", "").replace("open youtube and search", "").replace("open youtube", "").replace("youtube", "").replace("search for", "").strip()
            val = query if query else None
            actions.append(DeviceAction(domain="pc_automation", device_or_target="youtube", action="open_website", value=val))
            spoken = f"Opening YouTube for '{query}', sir." if query else "Opening YouTube, sir."

        # 9. Individual App Launches (Notepad, Calculator, VS Code, Paint, Browser, etc.)
        elif any(w in p_lower for w in ["open", "launch", "start"]):
            if "notepad" in p_lower:
                actions.append(DeviceAction(domain="pc_automation", device_or_target="notepad", action="open_app"))
                spoken = "Launching Notepad, sir."
            elif "calc" in p_lower or "calculator" in p_lower:
                actions.append(DeviceAction(domain="pc_automation", device_or_target="calculator", action="open_app"))
                spoken = "Launching Calculator, sir."
            elif "code" in p_lower or "vscode" in p_lower:
                actions.append(DeviceAction(domain="pc_automation", device_or_target="code", action="open_app"))
                spoken = "Launching Visual Studio Code, sir."
            elif "paint" in p_lower:
                actions.append(DeviceAction(domain="pc_automation", device_or_target="paint", action="open_app"))
                spoken = "Launching Paint, sir."
            elif "task manager" in p_lower:
                actions.append(DeviceAction(domain="pc_automation", device_or_target="task_manager", action="system_control"))
                spoken = "Opening Task Manager, sir."
            elif "explorer" in p_lower or "files" in p_lower:
                actions.append(DeviceAction(domain="pc_automation", device_or_target="explorer", action="system_control"))
                spoken = "Opening File Explorer, sir."
            elif any(b in p_lower for b in ["brave", "chrome", "edge", "browser"]):
                target_b = "brave" if "brave" in p_lower else ("chrome" if "chrome" in p_lower else "browser")
                actions.append(DeviceAction(domain="pc_automation", device_or_target=target_b, action="open_app"))
                spoken = f"Launching {target_b.capitalize()} browser, sir."

        # 10. Smart Home Direct Controls
        elif "temperature" in p_lower or "thermostat" in p_lower or "temp" in p_lower:
            # Extract number
            numbers = [float(s) for s in p_lower.split() if s.replace('.', '', 1).isdigit()]
            target_temp = numbers[0] if numbers else 22.0
            actions.append(DeviceAction(domain="smart_home", device_or_target="thermostat", action="set_temperature", value=target_temp))
            spoken = f"Thermostat target set to {target_temp:.1f}°C."

        elif "light" in p_lower:
            target_light = "living_room_light"
            if "kitchen" in p_lower:
                target_light = "kitchen_light"
            elif "bedroom" in p_lower:
                target_light = "bedroom_light"

            if "off" in p_lower or "turn off" in p_lower or "deactivate" in p_lower:
                actions.append(DeviceAction(domain="smart_home", device_or_target=target_light, action="turn_off"))
                spoken = f"Turning off the {target_light.replace('_', ' ')}."
            else:
                actions.append(DeviceAction(domain="smart_home", device_or_target=target_light, action="turn_on", value=100))
                spoken = f"Turning on the {target_light.replace('_', ' ')}."

        elif "door" in p_lower or "lock" in p_lower:
            if "unlock" in p_lower:
                actions.append(DeviceAction(domain="smart_home", device_or_target="front_door_lock", action="unlock"))
                spoken = "Front door unlocked, sir."
            elif "lock" in p_lower:
                if "pc" in p_lower or "workstation" in p_lower:
                    actions.append(DeviceAction(domain="pc_automation", device_or_target="lock_pc", action="system_control"))
                    spoken = "Workstation locked, sir."
                else:
                    actions.append(DeviceAction(domain="smart_home", device_or_target="front_door_lock", action="lock"))
                    spoken = "Front door locked and secured, sir."

        elif "fan" in p_lower:
            if "off" in p_lower:
                actions.append(DeviceAction(domain="smart_home", device_or_target="ceiling_fan", action="turn_off"))
                spoken = "Ceiling fan turned off."
            else:
                speed = "HIGH" if "high" in p_lower else ("LOW" if "low" in p_lower else "MEDIUM")
                actions.append(DeviceAction(domain="smart_home", device_or_target="ceiling_fan", action="set_speed", value=speed))
                spoken = f"Ceiling fan speed set to {speed}."

        elif "blinds" in p_lower:
            if "close" in p_lower or "shut" in p_lower:
                actions.append(DeviceAction(domain="smart_home", device_or_target="window_blinds", action="close"))
                spoken = "Window blinds closed."
            else:
                actions.append(DeviceAction(domain="smart_home", device_or_target="window_blinds", action="open"))
                spoken = "Window blinds opened."

        # Default conversational reply if no physical actions
        if not actions:
            if any(w in p_lower for w in ["who are you", "who created you", "identity"]):
                spoken = "I am JARVIS, an autonomous AI smart-home and desktop workstation assistant created and developed by Christian Ezekiel Carvajal and John Miko Sarsalijo."
            else:
                spoken = f"I have processed your statement: '{prompt}', sir."

        return AssistantIntentResponse(
            spoken_response=spoken,
            actions=actions,
            raw_prompt=prompt,
            interpreted_intent="agentic_action_plan" if actions else "conversational_dialogue",
            model_name=self.model_name
        )

    # Alias for backward compatibility
    def parse_intent(self, prompt: str) -> AssistantIntentResponse:
        return self.parse_command(prompt)

    def _clean_llm_json(self, raw_text: str) -> str:
        """Extracts clean JSON substring from LLM response text without regular expressions."""
        text = raw_text.strip()

        # Remove think tags if any
        while "<think>" in text and "</think>" in text:
            start_idx = text.find("<think>")
            end_idx = text.find("</think>") + len("</think>")
            text = (text[:start_idx] + text[end_idx:]).strip()

        # Remove markdown code blocks if any
        if "```json" in text:
            start = text.find("```json") + 7
            end = text.find("```", start)
            if end != -1:
                candidate = text[start:end].strip()
                try:
                    json.loads(candidate)
                    return candidate
                except Exception:
                    pass
        elif "```" in text:
            start = text.find("```") + 3
            end = text.find("```", start)
            if end != -1:
                candidate = text[start:end].strip()
                try:
                    json.loads(candidate)
                    return candidate
                except Exception:
                    pass

        # Robust bracket-counting scanner: find first complete valid { ... }
        start_idx = text.find('{')
        if start_idx != -1:
            depth = 0
            in_string = False
            escape = False
            for i in range(start_idx, len(text)):
                char = text[i]
                if in_string:
                    if escape:
                        escape = False
                    elif char == '\\':
                        escape = True
                    elif char == '"':
                        in_string = False
                else:
                    if char == '"':
                        in_string = True
                    elif char == '{':
                        depth += 1
                    elif char == '}':
                        depth -= 1
                        if depth == 0:
                            candidate = text[start_idx:i+1]
                            try:
                                json.loads(candidate)
                                return candidate
                            except Exception:
                                pass

        first_brace = text.find('{')
        last_brace = text.rfind('}')
        if first_brace != -1 and last_brace != -1 and last_brace > first_brace:
            candidate = text[first_brace:last_brace + 1]
            try:
                json.loads(candidate)
                return candidate
            except Exception:
                pass

        # If no JSON braces found but text exists, wrap as conversational JSON
        if text:
            return json.dumps({"spoken_response": text, "actions": []})
        return "{}"

