"""
AI Engine Module for Project JARVIS (Apex Home Automations & Stark PC Suite).
100% Pure Agentic AI Reasoning Engine interfacing directly with local Ollama (qwen3.5:2b).
Zero hardcoded trigger rules, keyword dictionaries, or regular expression matching.
All intent classification, tool selection, and parameter extraction are decided dynamically by the local LLM.
"""

import os
import sys
import time
import json
import shutil
import subprocess
import webbrowser
import urllib.parse
from typing import List, Optional, Any, Dict, Tuple
from pydantic import BaseModel, Field, model_validator
import requests
import psutil
import ollama

try:
    import pyautogui
    PYAUTOGUI_AVAILABLE = True
    pyautogui.FAILSAFE = False
except ImportError:
    PYAUTOGUI_AVAILABLE = False

try:
    import win32api
    import win32con
    WIN32_AVAILABLE = True
except ImportError:
    WIN32_AVAILABLE = False

DEFAULT_MODEL = "qwen3.5:2b"
CUSTOM_MODEL_CANDIDATES = ["jarvis-custom", "jarvis-trained-model", "qwen3.5:2b", "qwen3.5:4b", "qwen3.5:9b"]


class DeviceAction(BaseModel):
    """Pydantic v2 schema representing an agentic action decided by the LLM."""
    domain: str = Field(default="smart_home", description="Target domain: 'smart_home' or 'pc_automation'")
    device_or_target: str = Field(default="living_room_light", description="Target identifier (e.g. living_room_light, kitchen_light, bedroom_light, thermostat, front_door_lock, notepad, calculator, brave, spotify, youtube, lock_pc)")
    action: str = Field(default="turn_on", description="Action to perform (e.g. turn_on, turn_off, set_temperature, open_app, close_app, open_website, system_control, media_control, web_search)")
    value: Optional[Any] = Field(default=None, description="Action parameter (e.g. temperature float in °C, brightness level, URL, search query string, fan speed)")

    @model_validator(mode="before")
    @classmethod
    def sanitize_action(cls, values: Any) -> Any:
        if not isinstance(values, dict):
            return values

        target = str(values.get("device_or_target") or values.get("target") or values.get("device") or values.get("entity") or "").lower().strip()
        act = str(values.get("action") or "turn_on").lower().strip()
        domain = str(values.get("domain") or "").lower().strip()

        pc_targets = [
            "youtube", "spotify", "google", "github", "canvas", "browser", "chrome", "edge", "brave",
            "firefox", "notepad", "calculator", "calc", "paint", "mspaint", "terminal", "cmd", "powershell",
            "explorer", "file_explorer", "vscode", "code", "task_manager", "lock_pc", "web_search",
            "discord", "steam", "volume", "media", "screenshot"
        ]
        pc_actions = ["open_app", "close_app", "open_website", "system_control", "web_search", "media_control", "launch", "open", "close", "kill", "search"]

        if not domain:
            if any(pt in target for pt in pc_targets) or act in pc_actions:
                domain = "pc_automation"
            else:
                domain = "smart_home"

        values["domain"] = domain
        values["device_or_target"] = target if target else ("browser" if domain == "pc_automation" else "living_room_light")
        values["action"] = act
        return values

    @property
    def target(self) -> str:
        return self.device_or_target


class AssistantIntentResponse(BaseModel):
    """Authoritative Pydantic v2 schema for multi-action agentic plans generated by local LLM."""
    spoken_response: str = Field(default="Executing command, sir.")
    actions: List[DeviceAction] = Field(default_factory=list)
    raw_prompt: Optional[str] = Field(default="")
    interpreted_intent: Optional[str] = Field(default="agentic_action_plan")
    model_name: Optional[str] = Field(default=DEFAULT_MODEL)
    prompt_eval_count: Optional[int] = Field(default=None)
    eval_count: Optional[int] = Field(default=None)
    eval_duration_ms: Optional[float] = Field(default=None)

    @model_validator(mode="before")
    @classmethod
    def sanitize_plan(cls, values: Any) -> Any:
        if isinstance(values, dict):
            if not values.get("spoken_response"):
                values["spoken_response"] = "Command executed successfully, sir."
            if not values.get("interpreted_intent"):
                values["interpreted_intent"] = "agentic_action_plan"
        return values


# Backward compatibility alias
ActionPlan = AssistantIntentResponse


class PCAutomationEngine:
    """
    Dynamic Universal PC Desktop Automation Engine.
    Executes actions decided by the LLM (opening apps, closing processes, web navigation, system controls).
    Zero hardcoded user paths or regular expressions.
    """

    KNOWN_PROCESS_MAP = {
        "brave": "brave.exe",
        "chrome": "chrome.exe",
        "google chrome": "chrome.exe",
        "edge": "msedge.exe",
        "msedge": "msedge.exe",
        "microsoft edge": "msedge.exe",
        "firefox": "firefox.exe",
        "spotify": "Spotify.exe",
        "notepad": "notepad.exe",
        "calculator": "calc.exe",
        "calc": "calc.exe",
        "paint": "mspaint.exe",
        "mspaint": "mspaint.exe",
        "cmd": "cmd.exe",
        "powershell": "powershell.exe",
        "terminal": "wt.exe",
        "code": "Code.exe",
        "vscode": "Code.exe",
        "vs code": "Code.exe",
        "discord": "Discord.exe",
        "steam": "steam.exe",
        "task manager": "taskmgr.exe",
        "explorer": "explorer.exe",
        "file explorer": "explorer.exe"
    }

    WEB_FALLBACKS = {
        "spotify": "https://open.spotify.com",
        "code": "https://vscode.dev",
        "vscode": "https://vscode.dev",
        "calculator": "https://www.google.com/search?q=calculator",
        "calc": "https://www.google.com/search?q=calculator",
        "youtube": "https://www.youtube.com",
        "github": "https://www.github.com",
        "canvas": "https://canvas.instructure.com",
        "google": "https://www.google.com"
    }

    _app_cache: Dict[str, str] = {}

    @classmethod
    def _scan_windows_apps(cls):
        """Discovers installed application executables and shortcuts across Windows."""
        if cls._app_cache:
            return

        search_roots = [
            r"C:\ProgramData\Microsoft\Windows\Start Menu\Programs",
            os.path.expandvars(r"%APPDATA%\Microsoft\Windows\Start Menu\Programs"),
            os.path.expandvars(r"%LOCALAPPDATA%\Microsoft\WindowsApps"),
            r"C:\Program Files\BraveSoftware\Brave-Browser\Application",
            r"C:\Program Files\Google\Chrome\Application",
            r"C:\Program Files (x86)\Google\Chrome\Application",
            r"C:\Program Files (x86)\Microsoft\Edge\Application",
            os.path.expandvars(r"%LOCALAPPDATA%\Programs")
        ]

        for root_dir in search_roots:
            if os.path.exists(root_dir):
                try:
                    for root, _, files in os.walk(root_dir):
                        for file in files:
                            fl = file.lower()
                            if fl.endswith(".lnk") or fl.endswith(".exe") or fl.endswith(".url"):
                                if "." in file:
                                    key = file.rsplit(".", 1)[0].lower()
                                else:
                                    key = file.lower()
                                full_p = os.path.join(root, file)
                                if key not in cls._app_cache:
                                    cls._app_cache[key] = full_p
                except Exception:
                    pass

    @classmethod
    def resolve_app_path(cls, app_name: str) -> Optional[str]:
        """Resolves full executable or shortcut path for any target application."""
        clean = app_name.lower().strip()
        clean_exe = cls.KNOWN_PROCESS_MAP.get(clean, f"{clean}.exe")

        p_match = shutil.which(clean_exe) or shutil.which(clean)
        if p_match:
            return p_match

        cls._scan_windows_apps()
        if clean in cls._app_cache:
            return cls._app_cache[clean]

        for k, path in cls._app_cache.items():
            if clean in k or k in clean:
                return path

        return None

    @classmethod
    def launch_app(cls, app_name: str) -> Tuple[bool, str]:
        """Launches application dynamically on Windows desktop."""
        clean = app_name.lower().strip()

        if clean in ["brave", "chrome", "edge", "msedge", "firefox", "browser"]:
            target_browser = clean if clean != "browser" else "chrome"
            p = cls.resolve_app_path(target_browser)
            if p:
                try:
                    subprocess.Popen([p, "--new-window"])
                    return True, f"Launched {clean.capitalize()} browser window."
                except Exception:
                    pass
            webbrowser.open_new("https://google.com")
            return True, f"Opened default web browser."

        if clean == "spotify":
            try:
                os.system("start spotify:")
                return True, "Launched Spotify."
            except Exception:
                pass

        app_path = cls.resolve_app_path(clean)
        if app_path:
            try:
                os.startfile(app_path)
                return True, f"Launched '{clean.capitalize()}'."
            except Exception:
                try:
                    subprocess.Popen([app_path], shell=True)
                    return True, f"Launched '{clean.capitalize()}'."
                except Exception:
                    pass

        try:
            os.system(f"start {clean}:")
            return True, f"Launched '{clean.capitalize()}'."
        except Exception:
            pass

        if clean in cls.WEB_FALLBACKS:
            url = cls.WEB_FALLBACKS[clean]
            webbrowser.open(url)
            return True, f"Launched '{clean.capitalize()}' Web Fallback ({url})."

        return False, f"Could not locate '{clean}' on system."

    @classmethod
    def close_app(cls, app_name: str) -> Tuple[bool, str]:
        """Terminates active process gracefully or via taskkill without regular expressions."""
        clean = app_name.strip()
        if clean.lower().endswith(".exe"):
            clean = clean[:-4]
        clean = clean.lower()
        proc_exe = cls.KNOWN_PROCESS_MAP.get(clean, f"{clean}.exe")

        try:
            res = subprocess.run(["taskkill", "/IM", proc_exe], capture_output=True, text=True)
            if res.returncode == 0:
                return True, f"Closed {clean.capitalize()}."

            res_force = subprocess.run(["taskkill", "/F", "/IM", proc_exe], capture_output=True, text=True)
            if res_force.returncode == 0:
                return True, f"Force-closed {clean.capitalize()}."

            return True, f"No active process found for {clean.capitalize()}."
        except Exception as e:
            return False, f"Error closing {clean}: {e}"

    @classmethod
    def execute_pc_action(cls, target: str, action: str, value: Any = None) -> str:
        """Central execution router for LLM-decided PC automation actions."""
        target_clean = str(target or "").lower().strip()
        act_clean = str(action or "").lower().strip()

        # 1. Close Application
        if act_clean in ["close_app", "close", "kill", "terminate", "exit", "stop_app"]:
            _, msg = cls.close_app(target_clean)
            return f"PC Action: {msg}"

        # 2. Web Search
        if act_clean == "web_search" or "search" in target_clean:
            query = str(value or target_clean.replace("search", "")).strip()
            url = f"https://www.google.com/search?q={urllib.parse.quote(query)}"
            webbrowser.open_new(url)
            return f"PC Action: Searched Google for '{query}'"

        # 3. YouTube
        if "youtube" in target_clean or act_clean == "youtube":
            if value:
                query_str = urllib.parse.quote(str(value))
                url = f"https://www.youtube.com/results?search_query={query_str}"
            else:
                url = "https://www.youtube.com"
            webbrowser.open_new(url)
            return f"PC Action: Opened YouTube ({value if value else 'Home'})"

        # 4. Spotify
        if "spotify" in target_clean or act_clean == "spotify":
            if value:
                q = urllib.parse.quote(str(value))
                os.system(f"start spotify:search:{q}")
                return f"PC Action: Playing '{value}' on Spotify"
            else:
                os.system("start spotify:")
                return "PC Action: Opened Spotify"

        # 5. Media & Volume Controls
        if act_clean in ["media_control", "volume", "media"] or any(k in target_clean for k in ["volume", "mute", "pause", "play", "skip"]):
            if "up" in target_clean or "louder" in target_clean or (value and "up" in str(value)):
                if WIN32_AVAILABLE:
                    for _ in range(5):
                        win32api.keybd_event(win32con.VK_VOLUME_UP, 0, 0, 0)
                        win32api.keybd_event(win32con.VK_VOLUME_UP, 0, win32con.KEYEVENTF_KEYUP, 0)
                elif PYAUTOGUI_AVAILABLE:
                    for _ in range(5): pyautogui.press('volumeup')
                return "PC Action: Increased system volume"

            elif "down" in target_clean or "quieter" in target_clean or (value and "down" in str(value)):
                if WIN32_AVAILABLE:
                    for _ in range(5):
                        win32api.keybd_event(win32con.VK_VOLUME_DOWN, 0, 0, 0)
                        win32api.keybd_event(win32con.VK_VOLUME_DOWN, 0, win32con.KEYEVENTF_KEYUP, 0)
                elif PYAUTOGUI_AVAILABLE:
                    for _ in range(5): pyautogui.press('volumedown')
                return "PC Action: Decreased system volume"

            elif "mute" in target_clean:
                if WIN32_AVAILABLE:
                    win32api.keybd_event(win32con.VK_VOLUME_MUTE, 0, 0, 0)
                    win32api.keybd_event(win32con.VK_VOLUME_MUTE, 0, win32con.KEYEVENTF_KEYUP, 0)
                elif PYAUTOGUI_AVAILABLE:
                    pyautogui.press('volumemute')
                return "PC Action: Toggled volume mute"

            elif any(k in target_clean for k in ["pause", "play", "resume"]):
                if WIN32_AVAILABLE:
                    win32api.keybd_event(win32con.VK_MEDIA_PLAY_PAUSE, 0, 0, 0)
                    win32api.keybd_event(win32con.VK_MEDIA_PLAY_PAUSE, 0, win32con.KEYEVENTF_KEYUP, 0)
                elif PYAUTOGUI_AVAILABLE:
                    pyautogui.press('playpause')
                return "PC Action: Toggled media playback"

        # 6. System Controls
        if act_clean in ["system_control", "lock_pc", "open_task_manager", "open_explorer"] or target_clean in ["lock_pc", "lock", "task_manager", "open_task_manager", "file_explorer", "open_explorer", "screenshot"]:
            if target_clean in ["lock_pc", "lock"] or act_clean == "lock_pc":
                if sys.platform == "win32":
                    subprocess.Popen(["rundll32.exe", "user32.dll,LockWorkStation"], shell=True)
                return "PC Action: Workstation locked"
            elif target_clean in ["task_manager", "open_task_manager", "taskmgr"] or act_clean == "open_task_manager":
                subprocess.Popen(["taskmgr.exe"], shell=True)
                return "PC Action: Launched Task Manager"
            elif target_clean in ["file_explorer", "explorer", "open_explorer"] or act_clean == "open_explorer":
                subprocess.Popen(["explorer.exe"], shell=True)
                return "PC Action: Opened File Explorer"
            elif target_clean == "screenshot":
                if PYAUTOGUI_AVAILABLE:
                    pyautogui.screenshot("screenshot.png")
                    return "PC Action: Captured screen to screenshot.png"

        # 7. Open Website
        if act_clean == "open_website" or target_clean in ["github", "google", "canvas"]:
            if target_clean in cls.WEB_FALLBACKS:
                url = cls.WEB_FALLBACKS[target_clean]
            elif value and str(value).startswith("http"):
                url = str(value)
            else:
                url = f"https://www.{target_clean}.com" if not target_clean.startswith("http") else target_clean
            webbrowser.open_new(url)
            return f"PC Action: Opened website '{url}'"

        # 8. Dynamic Native Application Launcher
        _, msg = cls.launch_app(target_clean)
        return f"PC Action: {msg}"


class AIEngine:
    """
    Pure Agentic Local AI Engine interfacing directly with Ollama (qwen3.5:2b).
    Zero hardcoded regular expressions or keyword lookups. All decisions made dynamically by Qwen 3.5 (2B).
    """

    SYSTEM_PROMPT = """You are JARVIS, an autonomous AI smart-home and desktop agent for Apex Home Automations.
Do NOT think or output <think> tags. Always extract concrete actions and return ONLY a valid JSON object matching the schema:
{
  "spoken_response": "<Natural, concise spoken confirmation for the user>",
  "actions": [
    {
      "domain": "smart_home" | "pc_automation",
      "device_or_target": "<target_identifier>",
      "action": "<action_identifier>",
      "value": <numeric_value | string_parameter | null>
    }
  ]
}

Available Target Devices & Capabilities:
- Smart Home (domain: "smart_home"):
  * living_room_light, kitchen_light, bedroom_light: actions [turn_on, turn_off]
  * thermostat: action [set_temperature] (value: float in °C e.g. 24.0)
  * front_door_lock: actions [lock, unlock]
  * entertainment_unit: actions [turn_on, turn_off]
  * security_alarm: actions [arm, disarm]
  * ceiling_fan: actions [turn_on, turn_off, set_speed] (value: "low", "medium", "high")
  * window_blinds: actions [open, close]
- PC Desktop Automation (domain: "pc_automation"):
  * open_app: targets [notepad, calculator, paint, terminal, file_explorer, code, spotify, browser, brave, chrome]
  * open_website: targets [youtube, spotify, github, google, canvas] (value: optional search query)
  * system_control: targets [lock_pc, open_task_manager, open_explorer]

Contextual Reasoning Guidelines:
- Freezing / cold: set thermostat to 24.0°C and turn on living room light.
- Bed / goodnight: turn off lights and lock the front door.
- Movie mode: set living room light and turn on entertainment unit.
- Leaving / heading out: lock front door and lock PC.
- YouTube / web search: open website with search query string in value.
"""

    def __init__(self, model_name: Optional[str] = None, base_url: str = "http://localhost:11434"):
        self.base_url = base_url.rstrip("/")
        self.model_name = self._resolve_model_name(model_name)

    def _resolve_model_name(self, requested_model: Optional[str]) -> str:
        """Dynamically discovers fine-tuned or standardized models from local Ollama."""
        if requested_model:
            return requested_model

        try:
            resp = requests.get(f"{self.base_url}/api/tags", timeout=1.5)
            if resp.status_code == 200:
                available_models = [m.get("name", "").lower() for m in resp.json().get("models", [])]
                for candidate in CUSTOM_MODEL_CANDIDATES:
                    for avail in available_models:
                        if candidate in avail or avail.startswith(candidate):
                            return candidate
        except Exception:
            pass

        return DEFAULT_MODEL

    def _check_ollama_health(self) -> bool:
        """Verifies connection to local Ollama daemon."""
        try:
            resp = requests.get(f"{self.base_url}/api/tags", timeout=1.5)
            return resp.status_code == 200
        except Exception:
            return False

    def parse_command(self, prompt: str) -> AssistantIntentResponse:
        """
        Pure Agentic Intent Extraction:
        Sends prompt directly to local Qwen 3.5 (2B) via Ollama in strict JSON format.
        """
        clean_prompt = prompt.strip()
        if not clean_prompt:
            return AssistantIntentResponse(
                spoken_response="I am listening, sir. What can I do for you?",
                actions=[],
                raw_prompt="",
                interpreted_intent="empty_prompt",
                model_name=self.model_name
            )

        if self._check_ollama_health():
            try:
                resp = requests.post(
                    f"{self.base_url}/api/chat",
                    json={
                        "model": self.model_name,
                        "messages": [
                            {"role": "system", "content": self.SYSTEM_PROMPT},
                            {"role": "user", "content": clean_prompt}
                        ],
                        "stream": False,
                        "format": "json"
                    },
                    timeout=60.0
                )
                if resp.status_code == 200:
                    resp_json = resp.json()
                    msg = resp_json.get("message", {})
                    raw_content = msg.get("content", "").strip()
                    if not raw_content and msg.get("thinking"):
                        raw_content = msg.get("thinking", "").strip()

                    cleaned_json_str = self._clean_llm_json(raw_content)
                    parsed_data = json.loads(cleaned_json_str)

                    parsed_data["raw_prompt"] = clean_prompt
                    if "interpreted_intent" not in parsed_data:
                        parsed_data["interpreted_intent"] = "agentic_action_plan"

                    parsed_data["model_name"] = self.model_name
                    parsed_data["prompt_eval_count"] = resp_json.get("prompt_eval_count")
                    parsed_data["eval_count"] = resp_json.get("eval_count")
                    eval_duration = resp_json.get("eval_duration")
                    parsed_data["eval_duration_ms"] = (eval_duration / 1e6) if eval_duration else None

                    # Strict Pydantic v2 validation
                    plan = AssistantIntentResponse.model_validate(parsed_data)
                    return plan
            except Exception as e:
                print(f"[AIEngine Agentic Parse Recovery: {e}]")

        # Resilient fallback
        return AssistantIntentResponse(
            spoken_response=f"I have received your command: '{clean_prompt}', sir.",
            actions=[],
            raw_prompt=clean_prompt,
            interpreted_intent="offline_fallback",
            model_name=self.model_name
        )

    # Alias for backward compatibility
    def parse_intent(self, prompt: str) -> AssistantIntentResponse:
        return self.parse_command(prompt)

    def _clean_llm_json(self, raw_text: str) -> str:
        """Extracts clean JSON substring from LLM response text without regular expressions."""
        text = raw_text.strip()

        # Remove think tags if any
        while "<think>" in text and "</think>" in text:
            start_idx = text.find("<think>")
            end_idx = text.find("</think>") + len("</think>")
            text = (text[:start_idx] + text[end_idx:]).strip()

        # Remove markdown code blocks if any
        if "```json" in text:
            start = text.find("```json") + 7
            end = text.find("```", start)
            if end != -1:
                text = text[start:end].strip()
        elif "```" in text:
            start = text.find("```") + 3
            end = text.find("```", start)
            if end != -1:
                text = text[start:end].strip()

        first_brace = text.find('{')
        last_brace = text.rfind('}')
        if first_brace != -1 and last_brace != -1 and last_brace > first_brace:
            text = text[first_brace:last_brace + 1]
        return text
